[package]
name = "ds4net-rust"
version = "0.1.0"
authors = ["Yaroslav Isakov <yaroslav.isakov@gmail.com>"]
edition = "2018"

[dependencies]
crc = "1.8.1"
crossbeam-channel = "0.3"
parking_lot = "0.6"
signal-hook = "0.1"
